site_name: Redocs
site_url: https://docs.redux.wtf
theme:
  name: material
  features:
    - content.action.edit
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.indexes
    - content.code.copy
  favicon: assets/redocs_rounded_logo.png
  logo: assets/redocs_icon_logo_light.png
  palette: 
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Inter
    code: JetBrains Mono
  custom_dir: overrides
  
plugins:
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: true
      enabled: true
  - search:
  - blog:
      blog_dir: guides
      archive: false
  - blog:
      blog_dir: changelogs
      archive: false
      post_url_format: "{slug}"

repo_url: https://github.com/Inventor-Redux/Redocs
repo_name: Inventor-Redux/Redocs
edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      anchorlink: true
      permalink: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Inventor-Redux/Redocs
    - icon: fontawesome/brands/discord
      link: https://redux.wtf/join
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/_itsastro_
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@its_astro
    - icon: fontawesome/solid/house-chimney
      link: https://redux.wtf
copyright: Copyright &copy; 2024 Inventor Redux
site_description: Official Documentation for Inventor Redux