site_name: Redocs
site_url: https://docs.redux.wtf
theme:
  name: material
  features:
    - content.action.edit
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.indexes
  favicon: assets/redocs_rounded_logo.png
  logo: assets/redocs_icon_logo_light.png
  palette: 
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Inter
    code: JetBrains Mono
  custom_dir: overrides
  
plugins:
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: true
      enable_creation_date: true
      enabled: true
  - search:
  - blog:
      blog_dir: guides
      archive: false
  - blog:
      blog_dir: changelogs
      archive: false
      post_url_format: "{slug}"
  - tags:

repo_url: https://github.com/its-astro/Redocs
repo_name: its-astro/Redocs
edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      anchorlink: true
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/its-astro/Redocs
    - icon: fontawesome/brands/discord
      link: https://redux.wtf/join
copyright: Copyright &copy; 2024 Inventor Redux
site_description: Official Documentation for Inventor Redux
nav:
  - Home:
    - index.md
  - Getting Started:
    - getting-started/index.md
    - getting-started/test.md
  - Guides:
    - guides/index.md
  - Changelogs:
    - changelogs/index.md